require:
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
Naming/FileName:
  Exclude:
    - 'lib/adfs-open-id-connect.rb'
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Style/Documentation:
  Enabled: false
